# Autogenerated wrapper script for MPark_Variant_jll for aarch64-unknown-freebsd
JLLWrappers.@generate_wrapper_header("MPark_Variant")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
