# Autogenerated wrapper script for MPark_Variant_jll for powerpc64le-linux-gnu
JLLWrappers.@generate_wrapper_header("MPark_Variant")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
